# Generated by Django 4.2.20 on 2025-05-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstic', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
