# Generated by Django 4.2.20 on 2025-05-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstic', '0006_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
