# Generated by Django 4.2.20 on 2025-05-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstic', '0007_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
