# Generated by Django 4.2.20 on 2025-05-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstic', '0008_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
